# Generated by Django 3.2.5 on 2021-08-05 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='keyword',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
